# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
        - name: my-webapp-container
          image: com.illizen.tutorials/sample_crm:0.0.1-SNAPSHOT # Replace with your image
          ports:
            - containerPort: 8080 # Replace with your web app port
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"